services:
  db:
    container_name: mysql_playground_db
    image: mysql:latest
    #restart: always
    env_file:
      - ./.env.local
    ports:
      - "3640:3306"
    volumes:
      - db_data:/var/lib/mysql
  pma:
    container_name: mysql_playground_pma
    image: phpmyadmin:latest
    #restart: always
    environment:
      UPLOAD_LIMIT: 950M
    ports:
      - "8895:80"
    links:
      - db

volumes:
  db_data:
  
